name: 'Run size-limit'
description: 'size-limit action'
author: 'fryorcraken.eth <git@fryocraken.xyz>'
branding:
  icon: 'activity'
  color: 'green'
inputs:
  github_token:
    required: true
    description: 'a github access token'
  build_script:
    required: false
    default: "build"
    description: 'a custom npm script to build'
  clean_script:
    required: false
    description: 'a npm script to clean up build directory'
  skip_install:
    required: false
    default: 'false'
    description: 'Whether to skip `install` step'
  skip_build:
    required: false
    default: 'false'
    description: 'Whether to skip `build` step'
  directory:
    required: false
    description: "a custom subdirectory"
  windows_verbatim_arguments:
    required: false
    default: "true"
    description: "exec `size-limit` with the option `windowsVerbatimArguments`"
  script:
    required: false
    default: "npx size-limit --json"
    description: "The script used to generate size-limit results"
runs:
  using: 'node16'
  main: 'dist/index.js'
